apiVersion: 1

datasources:
  - name: Prometheus-EC2
    type: prometheus
    access: proxy
    url: http://prometheus.service.kandula.consul:9090
    isDefault: true
  - name: Prometheus-K8s
    type: prometheus
    access: proxy
    url: http://prometheus-operated-default.service.kandula.consul:9090
    isDefault: false
