---
- name: Copy Filebeat K8s config file
  copy:
    src: filebeat-k8s-config.yaml
    dest: /home/ubuntu/filebeat-k8s-config.yaml

- name: Copy Filebeat K8
  replace:
    path: /home/ubuntu/filebeat-k8s-config.yaml
    regexp: "<you elk host private ip>"
    replace: "{{ elk_private_ip }}"

- name: Deploy filebeat on K8s
  shell: "kubectl apply -f filebeat-k8s-config.yaml"
  become: false
