---
- name: Install Helm Prerequisites
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    update_cache: yes
    state: present

- name: Add GPG key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc

- name: Setup Helm Stable repo
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    update_cache: yes

- name: Install Helm
  apt:
    name:
      - helm
    update_cache: yes
    state: present
