apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanduka-app-deployment
  annotations:
    kubernetes.io/change-cause: "First deploy of Kandula app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kandula-app
  template:
    metadata:
      labels:
        app: kandula-app
    spec:
      containers:
        - name: kuard
          image: benbense/kandula-app:v1.0
          env:
            - name: FLASK_ENV
              value: "development"
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
            - name: AWS_DEFAULT_REGION
              value: ""
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
