---
- name: Copy Kubernetes node-exporter config file
  copy:
    src: node_exporter_k8s.yaml
    dest: /home/ubuntu/node_exporter_k8s.yaml

- name: Copy Kubernetes state metrics config file
  copy:
    src: kube_state_metrics.yaml
    dest: /home/ubuntu/kube_state_metrics.yaml

- name: Deploy node-exporter on K8s
  shell: "kubectl apply -f node_exporter_k8s.yaml"
  become: false

- name: Deploy node-exporter on K8s
  shell: "kubectl apply -f kube_state_metrics.yaml"
  become: false
