---
plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.service_role
    prefix: Service_Role
  - key: tags.instance_type
    prefix: Instance Type
  - key: tags.is_consul_monitored
    perfix: Should install Consul
compose:
  ansible_host: private_ip_address