---
- name: Add GPG key
  apt_key:
    url: https://www.pgadmin.org/static/packages_pgadmin_org.pub

- name: Setup pgAdmin4 Stable repo
  apt_repository:
    repo: "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bionic pgadmin4 main"
    update_cache: yes

- name: Install pgAdmin4
  apt:
    name:
      - pgadmin4-desktop
      - python-psycopg2
    update_cache: yes
    state: present

- name: Copy .sql file to machine
  copy:
    src: kandula.sql
    dest: /home/ubuntu/kandula.sql
    owner: ubuntu
    group: ubuntu

- name: Run SQL script to provision the database
  when: service == "ansible"
  postgresql_query:
    login_host: "rds.kandula"
    login_user: "postgres"
    login_password: "{{ db_password }}"
    port: "5432"
    db: "kandula"
    path_to_script: /home/ubuntu/kandula.sql
