---
- name: Add GPG key
  apt_key:
    url: https://www.pgadmin.org/static/packages_pgadmin_org.pub

- name: Setup pgAdmin4 Stable repo
  apt_repository:
    repo: "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bionic pgadmin4 main"
    update_cache: yes

- name: Install pgAdmin4
  apt:
    name:
      - pgadmin4-desktop
    update_cache: yes
    state: present

- name: Copy .sql file to machine
  copy:
    src: kandula.sql
    dest: /home/ubuntu/kandula.sql
    owner: ubuntu
    group: ubuntu

- name: Configure Database with SQL File
  command: psql -h rds.kandula -U postgres -d kandula -a -f /home/ubuntu/kandula.sql
  environment:
    PGPASSWORD: "{{ db_password }}"
