---
- name: Install Docker prerequisites
  apt:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - curl
    update_cache: yes
    state: present

- name: Install Docker Python
  pip:
    name:
      - docker

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Setup Docker's stable repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker engine
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    update_cache: yes

- name: Enable Docker Services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker.service
    - containerd.service

- name: Create Docker group
  group:
    name: "{{ docker_group }}"
    state: present

- name: Add docker users
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ docker_users }}"